# Generated by Django 4.1 on 2023-07-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
